# Generated by Django 6.0.8 on 2026-08-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Web Development', 'Web Development'), ('Full-Stack Development', 'Full-Stack Development'), ('Custom Software', 'Custom Software'), ('E-Commerce', 'E-Commerce'), ('Business Automation', 'Business Automation'), ('UI/UX Design', 'UI/UX Design')], default='Full-Stack Development', max_length=100)),
                ('technologies', models.CharField(help_text='Comma separated technologies e.g. React, Django, MySQL', max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('project_url', models.URLField(blank=True, help_text='Live project demo URL', null=True)),
                ('github_url', models.URLField(blank=True, help_text='Source code repository URL', null=True)),
                ('featured', models.BooleanField(default=False, help_text='Feature this project on home page hero/showcase')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-featured', '-created_at'],
            },
        ),
    ]
