# Generated by Django 6.0.8 on 2026-08-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150)),
                ('course_taken', models.CharField(help_text='e.g. Python Full-Stack Development', max_length=150)),
                ('company_name', models.CharField(help_text='Company hired by', max_length=150)),
                ('role', models.CharField(help_text='Designation e.g. Software Engineer, Frontend Developer', max_length=150)),
                ('package', models.CharField(blank=True, help_text='e.g. 6.5 LPA / 8.0 LPA', max_length=50)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='placements/')),
                ('testimonial_quote', models.TextField(blank=True)),
                ('featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Placement Record',
                'verbose_name_plural': 'Placement Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
