# Generated by Django 6.0.8 on 2026-08-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='TS Technology', max_length=100)),
                ('tagline', models.CharField(default='Building Digital Solutions for a Smarter Future.', max_length=200)),
                ('description', models.TextField(default='TS Technology provides modern digital solutions, web development, software development, business automation, IT services, and technology solutions for businesses and organizations.')),
                ('email', models.EmailField(default='contact@tstechnology.com', max_length=254)),
                ('phone', models.CharField(default='+1 (555) 019-2834', max_length=50)),
                ('address', models.CharField(default='Innovation Tech Park, Tech Suite 400', max_length=255)),
                ('business_hours', models.CharField(default='Mon - Fri: 9:00 AM - 6:00 PM EST', max_length=150)),
                ('social_linkedin', models.URLField(blank=True, default='https://linkedin.com')),
                ('social_github', models.URLField(blank=True, default='https://github.com')),
                ('social_instagram', models.URLField(blank=True, default='https://instagram.com')),
                ('social_twitter', models.URLField(blank=True, default='https://twitter.com')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Website Setting',
                'verbose_name_plural': 'Website Settings',
            },
        ),
    ]
