# Generated by Django 6.0.8 on 2026-08-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesetting',
            name='address',
            field=models.CharField(default='Ram Nagar, Ananthapur', max_length=255),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='business_hours',
            field=models.CharField(default='Mon - Sat: 9:00 AM - 6:00 PM IST', max_length=150),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='description',
            field=models.TextField(default='TS Technology is a premier IT Coaching Centre & Technology Solutions Provider offering industry-grade software courses, live project training, placement assistance, and custom software development in Ram Nagar, Ananthapur.'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='email',
            field=models.EmailField(default='tstechnology2000@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='phone',
            field=models.CharField(default='8008066034', max_length=50),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='tagline',
            field=models.CharField(default='Empowering Minds, Building Digital Solutions for a Smarter Future.', max_length=200),
        ),
    ]
