# Generated by Django 6.0.8 on 2026-08-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('Full-Stack Development', 'Full-Stack Development'), ('Python & Django', 'Python & Django'), ('Frontend Engineering', 'Frontend Engineering'), ('Database & Cloud', 'Database & Cloud'), ('Software Testing / QA', 'Software Testing / QA'), ('Data Science & AI', 'Data Science & AI')], default='Full-Stack Development', max_length=100)),
                ('duration', models.CharField(default='3 Months (12 Weeks)', max_length=100)),
                ('mode', models.CharField(choices=[('Classroom & Online', 'Classroom & Online'), ('Classroom Training', 'Classroom Training'), ('Online Live Classes', 'Online Live Classes')], default='Classroom & Online', max_length=100)),
                ('short_description', models.CharField(max_length=255)),
                ('full_description', models.TextField()),
                ('syllabus', models.TextField(help_text='Comma or newline separated syllabus modules')),
                ('prerequisites', models.CharField(default='Basic computer literacy & passion to learn programming', max_length=250)),
                ('icon', models.CharField(default='BookOpen', help_text='Lucide icon name', max_length=50)),
                ('featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['order', '-featured', 'title'],
            },
        ),
    ]
